name: Deploy Podman Container
on:  
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.CR_PAT }} | podman login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Podman Image
        run: |
          podman build -t ghcr.io/thee-sen-programmer256/localhost/realtime_dash:latest .
          podman push ghcr.io/thee-sen-programmer256/localhost/realtime_dash:latest
